POST http://localhost:3001/api/homes
Content-Type: application/json

{
    "title": "Split Lakefront Home w/Hot Tub, Private Dock, & Fire Pit!",
    "description": "Entire Chalet in Swanton",
    "owner": "Lakehouse Lady",
    "rating": 4.6,
    "pictureUrl": "https://airbnbcloneapp.s3.amazonaws.com/1237179fb1b4446fa6ba6d67c0bc2218",
    "price": 385,
    "bedrooms": 4,
    "beds": 7,
    "baths": 3,
    "kitchens": 1,
    "guests": 12,
    "reviews": 2,
    "wifi": true,
    "Air_Conditioning": true,
    "Free parking": true
}

###
PUT http://localhost:3001/api/homes/616cab92ec6152adf6c4ddad
Content-Type: application/json

{
  "description": "Entire Chalet in Swanton",
    "title": "Split Lakefront Home w/Hot Tub, Private Dock, & Fire Pit!",
    "price": 385,
    "bedrooms": 4,
    "beds": 7,
    "baths": 3,
    "kitchens": 1,
    "owner": "Lakehouse Lady",
    "rating": 4.6,
    "pictureUrl": "https://airbnbcloneapp.s3.amazonaws.com/1237179fb1b4446fa6ba6d67c0bc2218",
    "guests": 12,
    "reviews": 2,
    "wifi": true,
    "air_conditioning": true,
    "parking": true
}   